// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnvOd_wqOUzMnG6slVNIE6IOaLOEpPcJ8',
    appId: '1:937450773163:web:4b2c5dac3b18a16a5635ee',
    messagingSenderId: '937450773163',
    projectId: 'easyshop-44888',
    authDomain: 'easyshop-44888.firebaseapp.com',
    storageBucket: 'easyshop-44888.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBbeju-v5ghfUj5_GNItFJzYfoS1hoA8g',
    appId: '1:937450773163:android:65f344005726317a5635ee',
    messagingSenderId: '937450773163',
    projectId: 'easyshop-44888',
    storageBucket: 'easyshop-44888.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8N0UpWaq6GVHHzTaL2trfwsZ2l25-veQ',
    appId: '1:937450773163:ios:57e373727c2930c35635ee',
    messagingSenderId: '937450773163',
    projectId: 'easyshop-44888',
    storageBucket: 'easyshop-44888.firebasestorage.app',
    iosBundleId: 'com.example.easyshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8N0UpWaq6GVHHzTaL2trfwsZ2l25-veQ',
    appId: '1:937450773163:ios:57e373727c2930c35635ee',
    messagingSenderId: '937450773163',
    projectId: 'easyshop-44888',
    storageBucket: 'easyshop-44888.firebasestorage.app',
    iosBundleId: 'com.example.easyshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnvOd_wqOUzMnG6slVNIE6IOaLOEpPcJ8',
    appId: '1:937450773163:web:6ba8ab313f8f80725635ee',
    messagingSenderId: '937450773163',
    projectId: 'easyshop-44888',
    authDomain: 'easyshop-44888.firebaseapp.com',
    storageBucket: 'easyshop-44888.firebasestorage.app',
  );
}
